# Generated by Django 5.1 on 2024-08-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_allowed', models.IntegerField(default=2)),
                ('premium_allowed', models.IntegerField(default=10)),
            ],
        ),
    ]
