# Generated by Django 5.1 on 2024-08-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_basicsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
