# Generated by Django 5.1 on 2024-08-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trackingrecord_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingrecord',
            name='lowest_info',
            field=models.JSONField(default={}),
        ),
    ]
